In [5]:
dataDir = "/Users/adeshghadge/Downloads/flight-delays/"

In [32]:
import pandas as pd
import numpy as np
from sklearn import tree
import matplotlib.pyplot as plt  
%matplotlib inline

In [239]:
import dill
dill.dump_session(dataDir+'FinalProject.db')

KeyboardInterrupt: 

In [ ]:
import dill
dill.load_session('FinalProject.db')

In [7]:
flight_data = pd.read_csv(dataDir+"flights.csv")

In [248]:
flight_data.head()

Empty DataFrame
Columns: [YEAR, MONTH, DAY, DAY_OF_WEEK, AIRLINE, FLIGHT_NUMBER, TAIL_NUMBER, ORIGIN_AIRPORT, DESTINATION_AIRPORT, SCHEDULED_DEPARTURE, DEPARTURE_TIME, DEPARTURE_DELAY, TAXI_OUT, WHEELS_OFF, SCHEDULED_TIME, ELAPSED_TIME, AIR_TIME, DISTANCE, WHEELS_ON, TAXI_IN, SCHEDULED_ARRIVAL, ARRIVAL_TIME, ARRIVAL_DELAY, DIVERTED, CANCELLED, CANCELLATION_REASON, AIR_SYSTEM_DELAY, SECURITY_DELAY, AIRLINE_DELAY, LATE_AIRCRAFT_DELAY, WEATHER_DELAY]
Index: []

[0 rows x 31 columns]

In [247]:
flight_data.shape

(0, 31)

In [246]:
flight_data = flight_data.iloc[0:0]

In [243]:
list(flight_data.columns.values)

['YEAR',
 'MONTH',
 'DAY',
 'DAY_OF_WEEK',
 'AIRLINE',
 'FLIGHT_NUMBER',
 'TAIL_NUMBER',
 'ORIGIN_AIRPORT',
 'DESTINATION_AIRPORT',
 'SCHEDULED_DEPARTURE',
 'DEPARTURE_TIME',
 'DEPARTURE_DELAY',
 'TAXI_OUT',
 'WHEELS_OFF',
 'SCHEDULED_TIME',
 'ELAPSED_TIME',
 'AIR_TIME',
 'DISTANCE',
 'WHEELS_ON',
 'TAXI_IN',
 'SCHEDULED_ARRIVAL',
 'ARRIVAL_TIME',
 'ARRIVAL_DELAY',
 'DIVERTED',
 'CANCELLED',
 'CANCELLATION_REASON',
 'AIR_SYSTEM_DELAY',
 'SECURITY_DELAY',
 'AIRLINE_DELAY',
 'LATE_AIRCRAFT_DELAY',
 'WEATHER_DELAY']

In [249]:
flight_data_clean = flight_data[flight_data["DEPARTURE_DELAY"].isnull() == False]

In [250]:
flight_data_clean.shape

(0, 31)

In [182]:
list(flight_data_clean.columns.values)

['DAY_OF_WEEK',
 'AIRLINE',
 'FLIGHT_NUMBER',
 'TAIL_NUMBER',
 'ORIGIN_AIRPORT',
 'DESTINATION_AIRPORT',
 'SCHEDULED_DEPARTURE',
 'DEPARTURE_TIME',
 'TAXI_OUT',
 'WHEELS_OFF',
 'SCHEDULED_TIME',
 'AIR_TIME',
 'DISTANCE',
 'DIVERTED',
 'CANCELLED',
 'CANCELLATION_REASON',
 'FLIGHT_DATE',
 'FLIGHT_STATUS']

In [256]:
flight_data_clean = flight_data_clean.assign(FLIGHT_DATE = pd.to_datetime(flight_data_clean[["YEAR", "MONTH", "DAY"]]))

In [257]:
def label_flight_status(row):
    if(row["DEPARTURE_DELAY"] > 0):
        return "DELAYED"
    elif(row["DEPARTURE_DELAY"] < 0):
        return "BEFORE TIME"
    elif(row["DEPARTURE_DELAY"] == 0):
        return "ON TIME"
    
    return "NA"

In [258]:
flight_data_clean = flight_data_clean.assign(FLIGHT_STATUS = flight_data_clean.apply(lambda row: label_flight_status(row), axis = 1))

ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series

In [259]:
flight_data_clean = flight_data_clean.drop(["YEAR", "MONTH", "DAY", "SCHEDULED_ARRIVAL", "ARRIVAL_TIME", "ARRIVAL_DELAY", "DAY"], axis=1)

In [260]:
flight_data_clean = flight_data_clean.drop(["WHEELS_ON", "TAXI_IN"], axis=1)

In [261]:
flight_data_clean = flight_data_clean.drop(["AIR_SYSTEM_DELAY", "SECURITY_DELAY", "AIRLINE_DELAY", "LATE_AIRCRAFT_DELAY", "WEATHER_DELAY"], axis=1)

In [262]:
flight_data_clean = flight_data_clean.drop(["ELAPSED_TIME"], axis=1)

In [263]:
flight_data_clean = flight_data_clean.drop(["DEPARTURE_DELAY"], axis=1)

In [264]:
flight_data_clean = flight_data_clean.drop(['DEPARTURE_TIME', 'TAXI_OUT', 'WHEELS_OFF', 'SCHEDULED_TIME',\
                                            'AIR_TIME', 'DIVERTED', 'CANCELLED', 'CANCELLATION_REASON'], axis=1)

In [265]:
from sklearn.preprocessing import LabelEncoder  
encoder = LabelEncoder()

In [266]:
str_columns = ['DAY_OF_WEEK',
 'AIRLINE',
 'FLIGHT_NUMBER',
 'TAIL_NUMBER',
 'ORIGIN_AIRPORT',
 'DESTINATION_AIRPORT',
 'SCHEDULED_DEPARTURE',
 'DEPARTURE_TIME',
 'WHEELS_OFF',
 'DIVERTED',
 'CANCELLED',
 'CANCELLATION_REASON',
 'FLIGHT_DATE',
 'FLIGHT_STATUS']

for col in str_columns:
    flight_data_clean[col] = flight_data_clean[col].astype(str)
    flight_data_clean[col] = encoder.fit_transform(flight_data_clean[col])


KeyError: 'DEPARTURE_TIME'

In [267]:
flight_data_clean = flight_data_clean.dropna()

In [268]:
flight_data_clean.head()

Empty DataFrame
Columns: [DAY_OF_WEEK, AIRLINE, FLIGHT_NUMBER, TAIL_NUMBER, ORIGIN_AIRPORT, DESTINATION_AIRPORT, SCHEDULED_DEPARTURE, DISTANCE, FLIGHT_DATE]
Index: []

In [269]:
flight_data_clean.shape

(0, 9)

In [270]:
print (flight_data_clean[flight_data_clean['WEATHER_DELAY'].apply(lambda x: isinstance(x, str))])

KeyError: 'WEATHER_DELAY'

In [271]:
np.any(np.isnan(flight_data_clean))

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [272]:
np.all(np.isfinite(flight_data_clean))

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [273]:
np.unique(np.where(np.isnan(flight_data_clean))[1])

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [274]:
X = flight_data_clean.drop('FLIGHT_STATUS', axis=1)
y = flight_data_clean['FLIGHT_STATUS']

KeyError: "['FLIGHT_STATUS'] not found in axis"

In [275]:
X_train.head()

DAY_OF_WEEK  AIRLINE  FLIGHT_NUMBER  TAIL_NUMBER  ORIGIN_AIRPORT  \
5476300            2        0           1246         3428             345   
3082365            6        0           6635          526             544   
4375591            2        3            556         4614             326   
5080081            5        0           1778         1425             482   
2533781            1       13            855         3279             391   

         DESTINATION_AIRPORT  SCHEDULED_DEPARTURE  DISTANCE  FLIGHT_DATE  
5476300                  391                  593       399          192  
3082365                  575                  532      2370            7  
4375591                  391                   95       547          105  
5080081                  510                  931      2342          161  
2533781                  502                  638       895          329

In [253]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)  

In [190]:
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(X_train, y_train)  

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [211]:
from sklearn.externals import joblib

joblib.dump(classifier, 'tree_bst_model.pkl', compress=True)
# bst = joblib.load('bst_model.pkl') # load it later

['tree_bst_model.pkl']

In [228]:
pd.Series(classifier.feature_importances_,index=list(X_train.columns.values)).sort_values(ascending=False)

TAIL_NUMBER            0.236625
FLIGHT_DATE            0.184549
SCHEDULED_DEPARTURE    0.139512
FLIGHT_NUMBER          0.110562
DISTANCE               0.087837
DAY_OF_WEEK            0.071107
DESTINATION_AIRPORT    0.067241
ORIGIN_AIRPORT         0.066016
AIRLINE                0.036552
dtype: float64

In [191]:
y_pred = classifier.predict(X_test)  

In [192]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  

[[623599 293545  63824]
 [282979 309280  42473]
 [ 53631  37022   7850]]


In [193]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.65      0.64      0.64    980968
           1       0.48      0.49      0.49    634732
           2       0.07      0.08      0.07     98503

   micro avg       0.55      0.55      0.55   1714203
   macro avg       0.40      0.40      0.40   1714203
weighted avg       0.55      0.55      0.55   1714203



In [176]:
np.where(y_pred!=np.asarray(y_test))

(array([   1283,    1445,    1451, ..., 1711095, 1711705, 1714125]),)

In [194]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.548785062212585


In [195]:
list(X_train.columns.values)

['DAY_OF_WEEK',
 'AIRLINE',
 'FLIGHT_NUMBER',
 'TAIL_NUMBER',
 'ORIGIN_AIRPORT',
 'DESTINATION_AIRPORT',
 'SCHEDULED_DEPARTURE',
 'DISTANCE',
 'FLIGHT_DATE']

In [196]:
X_train.head()

DAY_OF_WEEK  AIRLINE  FLIGHT_NUMBER  TAIL_NUMBER  ORIGIN_AIRPORT  \
1414261            2       10           3510         1743             457   
4312702            5        2           6821          461             563   
1750538            2        3           2522          885             522   
5756624            6       13           1334         3319             391   
626230             2        7           2574         2052             392   

         DESTINATION_AIRPORT  SCHEDULED_DEPARTURE  DISTANCE  FLIGHT_DATE  
1414261                  346                  394      1597          285  
4312702                  473                   14       427           99  
1750538                  437                  224       408           57  
5756624                  428                  808       836          214  
626230                   368                  110       685          226

In [197]:
from sklearn.ensemble import RandomForestClassifier

clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [212]:
from sklearn.externals import joblib

joblib.dump(clf, dataDir+'rf_bst_model.pkl', compress=True)
# bst = joblib.load('bst_model.pkl') # load it later

['/Users/adeshghadge/Downloads/flight-delays/rf_bst_model.pkl']

In [229]:
pd.Series(clf.feature_importances_,index=list(X_train.columns.values)).sort_values(ascending=False)

TAIL_NUMBER            0.212176
FLIGHT_DATE            0.202057
SCHEDULED_DEPARTURE    0.142501
FLIGHT_NUMBER          0.107052
DISTANCE               0.085480
DAY_OF_WEEK            0.085002
DESTINATION_AIRPORT    0.066288
ORIGIN_AIRPORT         0.065253
AIRLINE                0.034191
dtype: float64

In [198]:
y_pred_rf = clf.predict(X_test)

In [199]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_rf))

Accuracy: 0.646783957325941


In [225]:
print(confusion_matrix(y_test, y_pred_rf)) 

[[784995 191274   4699]
 [308480 322875   3377]
 [ 64783  32871    849]]


In [226]:
print(classification_report(y_test, y_pred_rf)) 

              precision    recall  f1-score   support

           0       0.68      0.80      0.73    980968
           1       0.59      0.51      0.55    634732
           2       0.10      0.01      0.02     98503

   micro avg       0.65      0.65      0.65   1714203
   macro avg       0.45      0.44      0.43   1714203
weighted avg       0.61      0.65      0.62   1714203



In [201]:
import xgboost as xgb

dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

In [202]:
from sklearn.datasets import dump_svmlight_file

dump_svmlight_file(X_train, y_train, 'dtrain.svm', zero_based=True)
dump_svmlight_file(X_test, y_test, 'dtest.svm', zero_based=True)
dtrain_svm = xgb.DMatrix('dtrain.svm')
dtest_svm = xgb.DMatrix('dtest.svm')

[14:36:52] 3999805x9 matrix with 34898188 entries loaded from dtrain.svm
[14:36:52] 1714203x9 matrix with 14956244 entries loaded from dtest.svm


In [218]:
param = {
    'max_depth': 5,  # the maximum depth of each tree
    'eta': 0.1,  # the training step for each iteration
    'silent': 1,  # logging mode - quiet
    'objective': 'multi:softprob',  # error evaluation for multiclass training
    'num_class': 3}  # the number of classes that exist in this datset
num_round = 250  # the number of training iterations

In [219]:
bst = xgb.train(param, dtrain_svm, num_round)

In [209]:
from sklearn.externals import joblib

joblib.dump(bst, 'xgboost_bst_model.pkl', compress=True)
# bst = joblib.load('bst_model.pkl') # load it later

['xgboost_bst_model.pkl']

In [237]:
bst.get_score()

{'f6': 2656,
 'f1': 3318,
 'f8': 4457,
 'f7': 2576,
 'f2': 1660,
 'f5': 1334,
 'f4': 3411,
 'f3': 2194,
 'f0': 1481}

In [220]:
preds = bst.predict(dtest_svm)
y_pred_xgb = np.asarray([np.argmax(line) for line in preds])

In [221]:
print(metrics.precision_score(y_test, y_pred_xgb, average='macro'))

0.42202284436591403


In [222]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_xgb))

Accuracy: 0.6444668455252966
